### ISSUE TITLE
How to make network work?

### ISSUE THREAD

**Issue by Drugoy** [hectorm/docker-qemu-reactos#1]
For some reason network doesn't seem to work: it pings default gw just fine, but pinging 8.8.8.8 gets no response.

**Comment by hectorm** [comment]
This image uses the [user networking backend](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29), which gives problems with ICMP traffic, however TCP and UDP traffic work correctly, so you will be able to browse the web.

**Comment by Drugoy** [comment]
Confirmed, thanks.
