### ISSUE TITLE
How persisten configuration and change network

### ISSUE THREAD

**Issue by dfpmola** [hectorm/docker-qemu-reactos#12]
Hello,

How can I persist the system configuration, i.e. downloaded files, installed programs after restarting the container. 

I also need to create another network card with a local ip, in order to port fordward, would it have to be configured from kvm and/or docker? I don't quite understand

And i need to create another NIC with a IP in my local network, any guide of how configure the kvm/docker to get that? Thanks in any case

**Comment by hectorm** [comment]
You need to persist the entire disk, which is located in `/var/lib/qemu/disk/reacts.qcow2`. You can define a volume for the `/var/lib/qemu/disk/` directory, for example.

Regarding port forwarding, you can define the [`VM_NET_EXTRA_OPTIONS`](https://github.com/hectorm/docker-qemu-reactos/blob/v56/scripts/service/qemu/run#L8) variable to add additional options, although this does not allow you to create a new NIC, it might work for your use case. If you want to forward a new port, you need to set this variable and also use the `--publish` option of Docker.

**Comment by BananaAcid** [comment]
add `--volume disks:/var/lib/qemu/disk:rw` to the docker command (the disk folder is the one in the docker container that hosts the qemu drives)

@hectorm It might be nice, to have this in the readme

**Comment by hectorm** [comment]
Done!
