### ISSUE TITLE
`--device /dev/kvm` wont work on MacOS and Win

### ISSUE THREAD

**Issue by BananaAcid** [hectorm/docker-qemu-reactos#14]
Is there anything that can be changed to make it work?

**Comment by BananaAcid** [comment]
it seems, it runs just fine without `--device /dev/kvm` ... is there something I am missing?

**Comment by hectorm** [comment]
I have added a note in the readme, even if the container works without KVM, the performance impact is very high, unfortunately this can only be used on Linux at the moment.
