### ISSUE TITLE
Cannot connect to VNC server

### ISSUE THREAD

**Issue by ldiqual** [hectorm/docker-qemu-reactos#3]
Followed the instructions to run the docker container and then connect using the vnc webpage, this is what I got:

![image](https://user-images.githubusercontent.com/941453/66971170-fd529180-f044-11e9-9e11-b47852ffea33.png)

![image](https://user-images.githubusercontent.com/941453/66971177-05aacc80-f045-11e9-8e91-5f1f830e2926.png)

**Comment by ldiqual** [comment]
Same thing when exposing 5900 locally and using vnc-viewer

![image](https://user-images.githubusercontent.com/941453/66971405-fd9f5c80-f045-11e9-8a24-91ecf5afca1c.png)

**Comment by hectorm** [comment]
Could you please include the full Docker command and the container log?

**Comment by ldiqual** [comment]
```
[ldiqual@ldiqual-mbp]$ docker run --detach   --name qemu-reactos   --restart on-failure:3   --publish 127.0.0.1:5900:5900/tcp   --privileged --env QEMU_KVM=true   hectormolinero/qemu-reactos:latest

10deb74007954cdde15371073c67bc1521f1bcc1e69c9fa622a876c0b13c495c
```

Not sure where to grab logs, is there a path in the container that I should get?

**Comment by Drugoy** [comment]
`docker logs qemu-reactos`

**Comment by hectorm** [comment]
Are you using macOS? I only ran this container on Linux, it's possible that's the problem.

Apart from including the full log as @Drugoy indicates, try running the container without the `--privileged` and `--env QEMU_KVM=true` options (without these options the virtualization will be slower).

**Comment by ldiqual** [comment]
Good catch! I'm indeed running it on macOS, and was getting these in the docker logs:

```
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
```

After removing `--privileged` and `--env QEMU_KVM=true` it worked perfectly. Thanks!

**Comment by hectorm** [comment]
I think hardware acceleration is not possible until Docker for macOS supports nested virtualization (moby/hyperkit#127).
