### ISSUE TITLE
ReactOS live cd

### ISSUE THREAD

**Issue by coderaiser** [hectorm/docker-qemu-reactos#4]
Would be amazing to have live cd with `ReactOs` in dockerfile, so there was no need to install system. Got the same problem as https://github.com/hectorm/docker-qemu-reactos/issues/3.

Thanks for such an interesting project :). 

Have a BSOD after black screen on mac os:

![image](https://user-images.githubusercontent.com/1573141/105401956-7456dc80-5c2f-11eb-83a2-a6f184f57176.png)

**Comment by hectorm** [comment]
You can't install from the live CD and anyway the installation is quite fast, that's why I include the boot CD.

Regarding macOS unfortunately there is nothing I can do if Docker doesn't support nested virtualization.

Anyway, thank you for your support!
