### ISSUE TITLE
blue screen after install without KVM kernel module in the host

### ISSUE THREAD

**Issue by giodegas** [hectorm/docker-qemu-reactos#5]
I started the container with this command:

    docker run --detach --name reactos --restart on-failure:3 --publish 0.0.0.0:6080:6080/tcp hectormolinero/qemu-reactos:latest

because with the KVM options it complained there is no kernel module.

but got this on VNC:

![immagine](https://user-images.githubusercontent.com/6838625/107615039-c21d9e00-6c4b-11eb-870f-28c112231d54.png)

Is there anyway to runnit in this configuration?

Thank you.

**Comment by giodegas** [comment]
the host machine is a CentOS 8 VPS.

**Comment by hectorm** [comment]
It seems that the 0.4.13 version no longer works correctly in the latest versions of QEMU. I've upgraded to 0.4.14-RC-64 and the crash no longer occurs.
