### ISSUE TITLE
Apple M1

### ISSUE THREAD

**Issue by brandonros** [hectorm/docker-qemu-reactos#6]
```
CONTAINER ID   IMAGE                                            COMMAND                  CREATED          STATUS                        PORTS     NAMES
4278b3c9ecfa   hectormolinero/qemu-reactos:latest               "/usr/local/bin/cont…"   32 seconds ago   Exited (1) 26 seconds ago               qemu-reactos
```

```
$ docker logs -f 4278b3c9ecfa
qemu-x86_64: unable to find CPU model '2'
qemu-x86_64: unable to find CPU model '2'
qemu-x86_64: unable to find CPU model '2'
qemu-x86_64: unable to find CPU model '2'
```

**Comment by hectorm** [comment]
This image is only built for amd64 architectures, but on Apple M1 I guess you are running it with Rosetta.

Could you share the command you are using to run the image?

On macOS it's important that you don't use the `--privileged` and `--env QEMU_KVM=true` options since hardware acceleration is not possible until Docker for macOS supports nested virtualization (moby/hyperkit#127).

**Comment by hectorm** [comment]
After some checks I have found that the `QEMU_CPU` variable conflicts with the variables currently supported by QEMU. I have solved it by renaming all these variables to `QEMU_VM_`. Thank you for bringing this to my attention!

Can you check if the image is working properly? However without KVM and emulating amd64 on arm64v8 you can expect very poor performance.

**Comment by brandonros** [comment]
```
$ docker pull hectormolinero/qemu-reactos
Using default tag: latest
latest: Pulling from hectormolinero/qemu-reactos
Digest: sha256:82f76c08ced93bad42db6f82d5c5db0c110192a7bf9c49d7fab392d51fa16ce9
Status: Image is up to date for hectormolinero/qemu-reactos:latest
docker.io/hectormolinero/qemu-reactos:latest

$ docker run \
>   --detach \
>   --name qemu-reactos \
>   --publish 127.0.0.1:6080:6080/tcp \
>   hectormolinero/qemu-reactos:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

$ docker logs 41c42e4b0fdb8600130c2415310c00fe72259178293d51896ac55c1092564942
qemu-x86_64: unable to find CPU model '2'
```

It's as if your v28 never pushed to Docker Hub?

**Comment by hectorm** [comment]
My GitLab runner is busy right now with other pipelines, wait for the image to be pushed to Docker Hub or build it locally.
